# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manzana_seg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubigeo', models.CharField(max_length=255)),
                ('zona', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('aeu', models.CharField(blank=True, max_length=255)),
                ('aeu_seccion', models.CharField(blank=True, max_length=255)),
                ('aeu_zona', models.CharField(blank=True, max_length=255)),
                ('aeu_viv', models.CharField(blank=True, max_length=255)),
                ('aer_ini', models.CharField(blank=True, max_length=255)),
                ('aer_fin', models.CharField(blank=True, max_length=255)),
                ('estado_seg', models.CharField(blank=True, max_length=255)),
                ('estado_rep', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'MANZANA_SEG',
                'managed': True,
            },
        ),
    ]
