# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manzana_seg', '0002_segmentacion_prueba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segmentacion_prueba',
            options={'managed': False},
        ),
    ]
