# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manzana_seg', '0005_auto_20160906_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segmentacion_prueba',
            options={'managed': True},
        ),
    ]
