# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manzana_seg', '0007_auto_20160906_1640'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='segmentacion_prueba',
            table='TEMPORAL',
        ),
    ]
