# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manzana_seg', '0008_auto_20160906_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('ccdd', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=50)),
                ('fec_carga', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TB_DEPARTAMENTO',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='manzana_seg',
            options={'managed': False},
        ),
    ]
