# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manzana_seg', '0013_auto_20161003_1029'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='zona',
            table='TB_ZONA_CENSAL',
        ),
    ]
