# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manzana_seg', '0014_auto_20161003_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaAeu',
            fields=[
                ('ubigeo', models.CharField(blank=True, db_column='UBIGEO', max_length=6, null=True)),
                ('codccpp', models.CharField(blank=True, db_column='CODCCPP', max_length=4, null=True)),
                ('aeu_final', models.IntegerField(blank=True, db_column='AEU_FINAL', null=True)),
                ('cant_viv', models.IntegerField(blank=True, db_column='CANT_VIV', null=True)),
                ('seccion', models.IntegerField(blank=True, db_column='SECCION', null=True)),
                ('llave_sec', models.CharField(blank=True, db_column='LLAVE_SECC', max_length=50, null=True)),
                ('llave_aeu', models.CharField(blank=True, db_column='LLAVE_AEU', max_length=50, null=True)),
                ('llave_ccpp', models.CharField(blank=True, db_column='LLAVE_CCPP', max_length=50, null=True)),
                ('est_croquis', models.CharField(blank=True, db_column='EST_CROQUIS', max_length=1, null=True)),
                ('est_seg', models.CharField(blank=True, db_column='EST_SEG', max_length=1, null=True)),
                ('est_legajos', models.CharField(blank=True, db_column='EST_LEGAJOS', max_length=1, null=True)),
                ('zona', models.CharField(db_column='ZONA', max_length=10, primary_key=True, serialize=False)),
                ('idmanzana', models.CharField(blank=True, db_column='IDMANZANA', max_length=20, null=True)),
                ('aeu', models.IntegerField(blank=True, db_column='AEU', null=True)),
                ('viv_aeu', models.IntegerField(blank=True, db_column='VIV_AEU', null=True)),
            ],
            options={
                'db_table': 'SEGM_ESP_AEU',
                'managed': False,
            },
        ),
    ]
